app/routes/admin.py
from datetime import datetime
from flask import Blueprint, render_template, request, redirect, url_for, flash, session, current_app
from werkzeug.security import check_password_hash, generate_password_hash
from werkzeug.utils import secure_filename
from app.db import get_db
from app.utils import login_required, allowed_file, admin_required
import sqlite3
import os

admin_bp = Blueprint("admin", __name__)

@admin_bp.route('/admin/dashboard')
@login_required
@admin_required
def admin_dashboard():
    db = get_db()
    stats = db.execute('''
        SELECT
            COUNT(*) AS total_users,
            SUM(CASE WHEN role = 'admin' THEN 1 ELSE 0 END) AS admins,
            SUM(CASE WHEN frozen = 1 THEN 1 ELSE 0 END) AS frozen_accounts,
            SUM(balance) AS total_balance
        FROM users
        JOIN accounts ON users.id = accounts.user_id
    ''').fetchone()

    users = db.execute('''
        SELECT users.id, firstname, name, email, role, balance, frozen
        FROM users
        JOIN accounts ON users.id = accounts.user_id
        ORDER BY email
    ''').fetchall()

    return render_template('admin_dashboard.html', stats=stats, users=users)


@admin_bp.route('/admin/user/<int:user_id>', methods=['GET', 'POST'])
def admin_edit_user(user_id):
    if session.get('role') != 'admin':
        return ("Accès interdit", 403)
    db = get_db()

    if request.method == 'POST':
        role = request.form['role']
        balance = float(request.form['balance'])
        frozen = 1 if 'frozen' in request.form else 0

        db.execute('UPDATE users SET role = ? WHERE id = ?', (role, user_id))
        db.execute('UPDATE accounts SET balance = ?, frozen = ? WHERE user_id = ?', (balance, frozen, user_id))
        db.commit()
        return redirect(url_for('admin.admin_dashboard'))

    user = db.execute('''
        SELECT firstname, name, email, role, balance, frozen
        FROM users
        JOIN accounts ON users.id = accounts.user_id
        WHERE users.id = ?
    ''', (user_id,)).fetchone()

    history = db.execute('''
        SELECT type, amount, date, reason
        FROM transactions
        WHERE user_id = ?
        ORDER BY date DESC
    ''', (session['user_id'],)).fetchall()

    loan_requests = db.execute("""
        SELECT loan_requests.*
        FROM loan_requests
        JOIN users ON users.id = loan_requests.user_id
        ORDER BY created_at DESC
    """).fetchall()


    return render_template('admin_user.html', user=user, loan_requests=loan_requests, transactions=history)


@admin_bp.route('/admin/toggle/<int:user_id>', methods=['POST'])
@login_required
@admin_required
def admin_toggle(user_id):
    db = get_db()
    frozen = db.execute('SELECT frozen FROM accounts WHERE user_id = ?', (user_id,)).fetchone()['frozen']
    db.execute('UPDATE accounts SET frozen = ? WHERE user_id = ?', (int(not frozen), user_id))
    db.commit()
    return redirect(url_for('admin'))

@admin_bp.route("/admin/update_loan_status", methods=["POST"])
@login_required
@admin_required
def update_loan_status():
    loan_id = request.form["loan_id"]
    action = request.form["action"]
    if action not in ["approve", "reject"]:
        flash("Action non reconnue", "error")
        return redirect (request.referrer) or redirect(url_for("admin.admin_dashboard"))

    new_status = "approved" if action == "approve" else "rejected"

    db = get_db()

    loan = db.execute ("SELECT status FROM loan_requests WHERE id = ?", (loan_id, )).fetchone ()

    if (loan):
        if loan["status"] == "waiting":
            db.execute("UPDATE loan_requests SET status = ? WHERE id = ?", (new_status, loan_id))
            db.commit()
            status_text = "approuvée" if (new_status == "approved") else "rejetée"
            flash(f"Demande #{loan_id} {status_text}.", "success")
        else:
            flash(f"Demande de prêt #{loan_id} à déjà été traitée.", "success")

    else:
        flash(f"Demande de prêt #{loan_id} n'existe pas.")

    return redirect (request.referrer) or redirect(url_for("admin.admin_dashboard"))

app/routes/home.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session, current_app
from werkzeug.security import check_password_hash, generate_password_hash
from werkzeug.utils import send_from_directory
from app.db import get_db
from app.utils import login_required
import sqlite3

import sys

home_bp = Blueprint("home", __name__)

@home_bp.route("/uploads/<path:filename>")
@login_required
def uploaded_file(filename):# TODO : maybe check if the user can open this particular file
    # print (current_app.config["UPLOAD_FOLDER"], sys.stderr)
    return send_from_directory(directory=current_app.config["UPLOAD_FOLDER"], path=filename, as_attchment=True)

@home_bp.route('/')
def index():
    if 'user_id' in session:
        return redirect(url_for('home.home'))
    return redirect(url_for('auth.login'))

@home_bp.route('/home')
@login_required
def home():
    db = get_db()
    
    account = db.execute('''SELECT balance, frozen FROM accounts WHERE user_id = ?''', (session['user_id'],)).fetchone ()
    if (not account):
        return redirect (url_for ("auth.login"))


    username = db.execute('''SELECT firstname || ' ' || name AS fullname FROM users WHERE id = ?''', (session['user_id'], )).fetchone ()["fullname"]
    role = session.get('role', 'client')

    return render_template('home.html',
                           balance=account['balance'],
                           frozen=bool(account['frozen']),
                           role=role,
                           username=username,
                           user_id=session['user_id'])

app/routes/user.py
from datetime import datetime
from flask import Blueprint, render_template, request, redirect, url_for, flash, session, current_app
from werkzeug.security import check_password_hash, generate_password_hash
from werkzeug.utils import secure_filename
from app.db import get_db
from app.utils import login_required, allowed_file
import sqlite3
import os
import sys

user_bp = Blueprint("user", __name__)

@user_bp.route('/history')
@login_required
def history():
    db = get_db()
    rows = db.execute('''
        SELECT type, amount, date, reason
        FROM transactions
        WHERE user_id = ?
        ORDER BY date DESC
    ''', (session['user_id'],)).fetchall()
    return render_template('history.html', transactions=rows)


@user_bp.route('/transaction', methods=['GET', 'POST'])
@login_required
def transaction():
    db = get_db()
    user_id = session['user_id']
    role = session.get('role')

    if request.method == 'POST':
        type_ = request.form['type']
        amount = float(request.form['amount'])
        now = datetime.now().isoformat(timespec='seconds')
        transfer_to = None
        reason = request.form['reason']

        if (len(reason) > 80):
            flash ("Motif trop long", "error")
            return (redirect (request.referrer))

        # Vérifie si compte gelé
        frozen = db.execute('SELECT frozen FROM accounts WHERE user_id = ?', (user_id,)).fetchone()['frozen']
        if frozen:
            flash ("Compte gelé, opétation impossible")
            return (redirect (request.referrer))

        # Logique par type
        if type_ == 'deposit':
            db.execute('UPDATE accounts SET balance = balance + ? WHERE user_id = ?', (amount, user_id))
            db.execute('INSERT INTO transactions (user_id, type, amount, date, reason) VALUES (?, ?, ?, ?, ?)', (user_id, type_, +amount, now, reason))

        elif type_ == 'transfer':
            if (request.form ['user-id-trans']):
                transfer_to = int(request.form ['user-id-trans'])

                if (transfer_to == user_id):
                    flash ("Bénéficiaire et émetteur sont identiques", "error")
                    return (redirect (request.referrer))

                cursor = db.execute('SELECT user_id FROM accounts WHERE user_id = ?', (transfer_to, ))

                if (cursor.fetchone ()):
                    db.execute('UPDATE accounts SET balance = balance - ? WHERE user_id = ?', (amount, user_id))
                    db.execute('UPDATE accounts SET balance = balance + ? WHERE user_id = ?', (amount, transfer_to))
                    db.execute('INSERT INTO transactions (user_id, type, amount, date, reason) VALUES (?, ?, ?, ?, ?)', (transfer_to, type_, +amount, now, reason))
                    db.execute('INSERT INTO transactions (user_id, type, amount, date, reason) VALUES (?, ?, ?, ?, ?)', (user_id, type_, -amount, now, reason))

                else:
                    flash ("ID bénéficiaire inconnu.", "error")
                    return (redirect (request.referrer))

            else:
                
                flash ("Bénéficiaire non précisé.", "error")
                return (redirect (request.referrer))

        else:
            flash ("Type de transaction invalide.", "error")
            return (redirect (request.referrer))

        db.commit()
        return redirect(url_for('home.home'))

    # GET
    acc = db.execute('SELECT frozen FROM accounts WHERE user_id = ?', (user_id,)).fetchone()
    return render_template('transaction.html', frozen=bool(acc['frozen']))

@user_bp.route("/loan_request", methods=["GET", "POST"])
@login_required
def loan_request():
    db = get_db()
    user_id = session["user_id"]
    cursor = db.cursor()

    if request.method == "POST":
        amount = float(request.form["amount"])
        duration = int(request.form["duration"])
        reason = request.form["reason"]

        if (len(reason) > 80): 
            flash ("Motif trop long.", "error.")
            return (redirect (request.referrer))
        
        if (amount <= 0): 
            flash ("Montant demandé est invalide.", "error")
            return (redirect (request.referrer))
        
        if (duration <= 0):
            flash ("Durée demandée est invalide.", "error")
            return (redirect (request.referrer))

        document = request.files.get("justification")
        file_path = None


        if document and allowed_file(document.filename):
            filename = secure_filename(document.filename)
            path = os.path.join(current_app.config["UPLOAD_FOLDER"], filename)
            document.save(path)
            file_path = filename

        elif document and document.filename:
            flash("Format de fichier non autorisé (PDF uniquement)", "error")
            return redirect(url_for('user.loan_request'))

        cursor.execute("""
            INSERT INTO loan_requests (user_id, amount, duration_months, reason, file_path)
            VALUES (?, ?, ?, ?, ?)
        """, (user_id, amount, duration, reason, file_path))
        db.commit()
        flash("Votre demande de prêt a bien été soumise.", "success")
        return redirect(url_for("user.loan_request"))

    # Affiche toutes les demandes de l'utilisateur
    cursor.execute("""
        SELECT * FROM loan_requests
        WHERE user_id = ?
        ORDER BY created_at DESC
    """, (user_id,))
    all_loans = cursor.fetchall()

    return render_template("loan_request.html", all_loans=all_loans)


@user_bp.route("/cancel_loan", methods=["POST"])
@login_required
def cancel_loan_request():
    if 'user_id' not in session:
        return redirect(url_for('login'))

    loan_id = request.form["loan_id"]
    user_id = session["user_id"]

    db = get_db()
    # Vérifie que le prêt appartient bien à l'utilisateur
    loan = db.execute("SELECT * FROM loan_requests WHERE id = ? AND user_id = ?", (loan_id, user_id)).fetchone()
    if not loan or loan["status"] != "waiting":
        flash("Impossible d'annuler cette demande.", "error")
        return redirect(url_for("user.loan_request"))

    db.execute("DELETE FROM loan_requests WHERE id = ?", (loan_id,))
    db.commit()
    flash("Votre demande a été annulée.", "success")
    return redirect(url_for("user.loan_request"))


@user_bp.route('/user_settings', methods=["GET", "POST"])
@login_required
def user_settings():
    db = get_db()

    user = db.execute('''
    SELECT firstname, name, email, password
    FROM users
    WHERE id = ?
    ''', (session['user_id'], )).fetchone()

    if request.method == "POST":
        firstname = request.form["first_name"]
        lastname = request.form["last_name"]
        email = request.form["email"]
        old_password = request.form["current_password"]
        new_password = request.form["new_password"]

        if new_password:
            if not check_password_hash (user ["password"], old_password):
                flash ("Mot de passe incorect", "error")
                return redirect (request.referrer)

            hashed_pw = generate_password_hash(new_password)
            db.execute(
                "UPDATE users SET firstname = ?, name = ?, email = ?, password = ? WHERE id = ?",
                (firstname, lastname, email, hashed_pw, session["user_id"]),
            )
        else:
            db.execute(
                "UPDATE users SET firstname = ?, name = ?, email = ? WHERE id = ?",
                (firstname, lastname, email, session["user_id"]),
            )
        db.commit()
        flash("Modifications enregistrées.", "success")
        return redirect(url_for("user.user_settings"))

    user = db.execute('''
    SELECT firstname, name, email
    FROM users
    WHERE id = ?
    ''', (session['user_id'], )).fetchone()

    return render_template('user_settings.html', user=user)

app/templates/admin_dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard Admin{% endblock %}
{% block content %}

<div class="column-center">
    <div class="widget">
        <h2>Dashboard Administrateur</h2>
    </div>

    <div class="row">
        <div class="widget">
            <h3>Utilisateurs</h3>
            <table class="styled-table">
                <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Email</th>
                        <th>Rôle</th>
                        <th>Solde (€)</th>
                        <th>Gelé</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for u in users %}
                    <tr>
                        <td>{{ u.firstname }}</td>
                        <td>{{ u.name }}</td>
                        <td>{{ u.email }}</td>
                        <td>{{ u.role }}</td>
                        <td>{{ '%.2f'|format(u.balance) }}</td>
                        <td>{{ 'Oui' if u.frozen else 'Non' }}</td>
                        <td>
                            <a class="btn" href="/admin/user/{{ u.id }}">Gérer</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="widget">
            <h3>Statistiques</h3>
            <ul class="stats">
                <li>Total utilisateurs : {{ stats.total_users }}</li>
                <li>Admins : {{ stats.admins }}</li>
                <li>Comptes gelés : {{ stats.frozen_accounts }}</li>
                <li>Solde total : {{ stats.total_balance }} €</li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

app/templates/admin_user.html
{% extends "base.html" %}
{% block title %}Modifier Utilisateur{% endblock %}
{% block content %}
<div class="column-center">
    <div class="row">
        <div class="column-center">            
            <div class="widget">
                <h2>Modifier Utilisateur</h2>
            </div>

            <div class="widget">
                <form method="post" class="column-center">
                    <div class="form-liner">
                        <label>Prénom</label>
                        <input type="text" value="{{ user.firstname }}" readonly>
                    </div>

                    <div class="form-liner">
                        <label>Nom</label>
                        <input type="text" value="{{ user.name }}" readonly>
                    </div>

                    <div class="form-liner">
                        <label>Email</label>
                        <input type="text" value="{{ user.email }}" readonly>
                    </div>
                    <div class="form-liner">
                        <label>Rôle</label>
                        <select name="role">
                            <option value="client" {% if user.role == 'client' %}selected{% endif %}>Utilisateur</option>
                            <option value="admin" {% if user.role == 'admin' %}selected{% endif %}>Admin</option>
                        </select>
                    </div>

                    <div class="form-liner">
                        <label>Solde (€)</label>
                        <input type="number" name="balance" value="{{ user.balance }}" step="0.01" class="number-textbox" required>
                    </div>

                    <div class="form-liner">
                        <label>Gelé</label>
                        <div class="flipswitch">
                            <input type="checkbox" name="frozen" class="flipswitch-cb" id="fs" {% if user.frozen %}checked{% endif %}>
                            <label class="flipswitch-label" for="fs">
                                <div class="flipswitch-inner"></div>
                                <div class="flipswitch-switch"></div>
                            </label>
                        </div>
                    </div>


                    <button type="submit" class="btn">Sauvegarder</button>
                    <a href="/admin/dashboard" class="danger-btn">Annuler</a>
                </form>
            </div>
        </div>

        <div class="column-center">
            <div class="widget">
                <h2>Historique des transactions</h2>
            </div>
            <div class="widget">
                {% if transactions %}
                <table class="styled-table">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Type</th>
                            <th>Montant (€)</th>
                            <th>Objet</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for t in transactions %}
                        <tr>
                            <td>{{ t['date'] }}</td>
                            <td class="type {{ t['type'] }}">{{ t['type'].capitalize() }}</td>
                            <td>{{ '%.2f' | format(t['amount']) }}</td>
                            <td>{{ t ['reason'] }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                    <p>Aucune transaction enregistrée.</p>
                {% endif %}
            </div>
        </div>
    </div>

    {% if loan_requests %}
    <div class="widget">
        <h3>📋 Demandes de prêt</h3>
        <table>
            <thead>
                <tr>
                    <th>Montant</th>
                    <th>Durée</th>
                    <th>Motif</th>
                    <th>Statut</th>
                    <th>Justificatif</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for loan in loan_requests %}
                <tr>
                    <td>{{ loan.amount }} €</td>
                    <td>{{ loan.duration_months }} mois</td>
                    <td>{{ loan.reason }}</td>
                    <td class="type {{loan.status}}">{% if loan.status == 'waiting' %}
                        En attente
                        {% elif loan.status == 'approved' %}
                        Validée
                        {% else %}
                        Refusée
                        {% endif %}
                    </td>
                    <td>
                        {% if loan.file_path %}
                        <a href="{{ url_for('uploaded_file', filename=loan.file_path) }}" target="_blank">Voir</a>
                        {% else %}
                        Aucun
                        {% endif %}
                    </td>
                    <td>
                        {% if loan.status == 'waiting' %}
                        <form method="POST" action="{{ url_for('admin.update_loan_status') }}">
                            <input type="hidden" name="loan_id" value="{{ loan.id }}">
                            <button name="action" value="approve" class="success-btn">Valider</button>
                            <button name="action" value="reject" class="danger-btn">Refuser</button>
                        </form>
                        {% else %}
                        -
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}
</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Banque{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>


<body>
    <div class="page-wrapper">
        <header>
            <div class="header-container">
                <h1>🏦 Ma Banque</h1>
                <nav>
                    {% if session.get('user_id') %}
                    <a href="/home">Accueil</a>
                    <a href="/logout">Déconnexion</a>
                    {% else %}
                    <a href="/login">Connexion</a>
                    <a href="/signup">Inscription</a>
                    {% endif %}
                </nav>
            </div>
        </header>
        
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            <div class="flash-messages">
                {% for category, message in messages %}
                <div class="flash {{ category }}">{{ message }}</div>
                {% endfor %}
            </div>
            {% endif %}
        {% endwith %}

        <div class="layout-container">
            {% block precontent %}{% endblock %}
            <main>
                <div class="info-box">
                    {% block content %}{% endblock %}
                </div>
            </main>
            {% block postcontent %}{% endblock %}
        </div>
        
        
        <footer>
            <p>&copy; 2025 Ma Banque — Tous droits réservés.</p>
        </footer>
    </div>
</body>
</html>

{% block scripts %}{% endblock %}

<script>
    number_textboxes = document.getElementsByClassName ("number-textbox");
    for (element of number_textboxes)
    {
        element.addEventListener('beforeinput', (e) => {
            const char = e.data;
            const value = element.value;

            if (e.inputType !== "insertText") return;
            console.log (value)

            if (/^\d$/.test(char)) return;

            if ((char === '.' || char === ',') && (!value.includes('.') || !value.includes(','))){
                return;
            }

            e.preventDefault();
        });    
    }
</script>

app/templates/history.html
{% extends "base.html" %}
{% block title %}Historique des Transactions{% endblock %}
{% block content %}

<div class="column-center">
    <div class="widget">
        <h2>Historique de vos transactions</h2>
    </div>
    <div  class="widget">

        {% if transactions %}
        <table class="styled-table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Type</th>
                    <th>Montant (€)</th>
                    <th>Objet</th>
                </tr>
            </thead>
            <tbody>
                {% for t in transactions %}
                <tr>
                    <td>{{ t['date'] }}</td>
                    <td class="type {{ t['type'] }}">{{ t['type'].capitalize() }}</td>
                    <td>{{ '%.2f' | format(t['amount']) }}</td>
                    <td>{{ t ['reason'] }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
            <p>Aucune transaction enregistrée.</p>
        {% endif %}

    </div>
</div>

{% endblock %}

app/templates/home.html
{% extends "base.html" %}
{% block title %}Accueil{% endblock %}

{% block postcontent %}
<div class="sidebar">
    <h2>Menu</h2>
    <nav>
        <ul>
            <li><a href="/transaction">💸 Transactions</a></li>
            <li><a href="/history">📜 Historique</a></li>
            <li><a href="/loan_request">🏦 Mes prêts</a></li>
            <li><a href="/user_settings">⚙️ Paramètres</a></li>
            {% if session.get('role') == 'admin' %}
            <li><a href="/admin/dashboard">🛠️ Admin Dashboard</a></li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}

{% block content %}

<div class="row-center">
    <div class="widget">
        <h1>Bienvenue {{ username }}</h1>
    </div>

    <div class="widget">
        <h3>Statistiques</h2>    
        <ul class="stats" class="column-center">
            <li>Solde : {{ balance }} €</li>
            <li>État du compte : {{ 'Gelé' if frozen else 'Actif' }}</li>
            <li>Numéro de compte : {{ '%010d' % user_id }}</li>
        </ul>
    </div>
</div>


<!--
    <form>
        <h2>Bienvenue !</h2>
        <p><strong>Solde :</strong> {{ balance }} €</p>
    <p><strong>État du compte :</strong> {{ 'Gelé' if frozen else 'Actif' }}</p>
    
    <div style="margin-top: 2rem;">
        <a href="/transactions" class="btn">Voir l'historique</a><br><br>
        <a href="/transact" class="btn">Faire une transaction</a><br><br>
        {% if session.get('role') == 'admin' %}
        <a href="/admin/dashboard" class="btn" >📊 Dashboard Administrateur</a><br><br>
        {% endif %}
        <form method="post" action="/toggle_freeze">
            <button class="btn" style="margin-top:1rem; background-color: #dc3545;">
                {% if frozen %}Dégeler le compte{% else %}Geler le compte{% endif %}
            </button>
        </form><br><br>
        <a href="/logout" class="btn">Se déconnecter</a>
    </div>
</form>
-->
{% endblock %}

app/templates/loan_request.html
{% extends "base.html" %}
{% set show_sidebar = True %}
{% block title %}Mes prêts{% endblock %}

{% block content %}

<div class="column-center">
    
    <div class="widget">
        <h2>Demande de prêt</h2>
    </div>

    <div class="widget">
        <form method="POST" enctype="multipart/form-data" class="column-center">
            <div class="form-liner">
                <label for="amount">Montant demandé (€)</label>
                <input type="number" id="amount" name="amount" step="0.01" min="0.01" class="number-textbox" required>
            </div>
            
            <div class="form-liner">
                <label for="duration">Durée (en mois)</label>
                <input type="number" id="duration" name="duration" min="1" class="number-textbox" required>
            </div>
            
            <div class="form-liner">
                <label for="reason">Motif</label>
                <textarea id="reason" name="reason" rows="2" maxlength="80" required></textarea>
            </div>
            
            <div class="form-liner">
                <label for="justification">Justificatif (PDF)</label>
                <input type="file" id="justification" name="justification" accept="application/pdf">
            </div>
            
            <button type="submit" class="btn">Soumettre la demande</button>
            <a href="/home" class="danger-btn">Annuler</a>
        </form>
    </div>
</div>

{% if all_loans %}
<div class="column-center">
        <div class="widget">
            <h2>Suivi de demande</h2>
        </div>

        <div class="widget">

            {% for loan in all_loans %}
            <div class="widget">
                <ul class="stats">
                    <li><strong>Montant :</strong> {{ loan.amount }} €</li>
                    <li><strong>Durée :</strong> {{ loan.duration_months }} mois</li>
                    <li><strong>Motif :</strong> {{ loan.reason }}</li>
                    <li><strong>Statut :</strong> {{ loan.status }}</li>
                    {% if loan.file_path %}
                    <li><a href="{{ url_for('home.uploaded_file', filename=loan.file_path) }}" target="_blank">Voir le justificatif</a></li>
                    {% endif %}
                </ul>
                
                {% if loan and loan.status == 'waiting' %}
                <form method="POST" action="{{ url_for('user.cancel_loan_request') }}">
                    <input type="hidden" name="loan_id" value="{{ loan.id }}">
                    <button type="submit" class="danger-btn">Annuler la demande</button>
                </form>
                {% endif %}
                
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% block title %}Connexion{% endblock %}
{% block content %}

<div class="column-center">
    <div class="widget">
        <h2>Connexion</h2>
    </div>
    
    <div class="widget">
        <form method="post" action="/login">
            <div class="single-liner">
                <input type="email" name="email" placeholder="Email" required>
            </div>
            <div class="single-liner">
                <input type="password" name="password" placeholder="Mot de passe" required>
            </div>
        
            <button type="submit" class="btn">Se connecter</button>
            <a href="/signup" class="link">Pas encore de compte ? Inscription</a>
        </form>
    </div>
</div>

{% endblock %}

app/templates/signup.html
{% extends "base.html" %}
{% block title %}Inscription{% endblock %}
{% block content %}
<form method="post" action="/signup" class="widget">
    <h2>Inscription</h2>
    <div class="single-liner">
        <input type="email" name="email" placeholder="Email" required>
    </div>
    <div class="single-liner">
        <input type="password" name="password" placeholder="Mot de passe" required>
    </div>

    <div class="single-liner">
        <input type="text" name="firstname" placeholder="Prénom" required>
    </div>

    <div class="single-liner">
        <input type="text" name="name" placeholder="Nom" required>
    </div>

    <button type="submit" class="btn">Créer un compte</button>
    <a href="/login" class="link">Déjà un compte ? Connexion</a>
</form>
{% endblock %}